<?php
/**
 * @file
 * Code for the GSB Feature Page Content Type feature.
 */

include_once 'gsb_feature_page_ct.features.inc';

/**
 * Implements hook_workbench_moderation_access_alter().
 */
function gsb_feature_page_ct_workbench_moderation_access_alter(&$access, $op, $node) {
  global $user;
  if ($user->uid == 1) {
    $access = TRUE;
    return;
  }
  if ($op == 'view revisions' && $node->type == 'page' && user_access('view revisions')) {
    foreach($node->workbench_access as $wb_access) {
      $flat_roles = implode(',', $user->roles);
      $pos = strpos($flat_roles, ':'.$wb_access.',');
      if ($pos !== false) {
        $access = TRUE;
        return;
      }
    }
    $access = FALSE;
  }
}
